# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#home
    weight: 10
  - name: Call For Papers
    url: /#cfp
    weight: 20
  - name: Speaker List
    url: /#speakers
    weight: 30
  - name: Schedule
    url: /#schedule
    weight: 40
  - name: Organizers
    url: /#organizers
    weight: 50
  # - parent: Resources
  #   name: Blog
  #   url: blog/
