# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: sky
  fonts: custom
  font_size: L

#
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'colm2025_workshop_praglm'
    description: 'Workshop on Pragmatic Reasoning in LLMs: Language Models as Language Users'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "praglm.svg"
    button:
      enable: false
      text: "Register for COLM 2025"
      url: "https://colmweb.org"
    show_search: false
    show_theme_chooser: false
  favicon:
    filename: "icon.png"

# Site footer
footer:
  copyright:
    notice: '© 2025 Workshop Organizers | Photo by <a href="https://unsplash.com/@venmer?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Stanislav</a> on <a href="https://unsplash.com/photos/a-computer-generated-image-of-a-blue-and-purple-object-QrdBlbeVoeg?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
      '

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
